sudo: false
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-django22
    - python: 3.7
      env: TOXENV=py37-django22
    - python: 3.8
      env: TOXENV=py38-django22
    - python: 3.6
      env: TOXENV=py36-django30
    - python: 3.7
      env: TOXENV=py37-django30
    - python: 3.8
      env: TOXENV=py38-django30
    - python: 3.6
      env: TOXENV=py36-django31
    - python: 3.7
      env: TOXENV=py37-django31
    - python: 3.8
      env: TOXENV=py38-django31
    - python: 3.6
      env: TOXENV=py36-djangomaster
    - python: 3.7
      env: TOXENV=py37-djangomaster
    - python: 3.8
      env: TOXENV=py38-djangomaster
    - env: TOXENV=black
    - env: TOXENV=flake8
    - env: TOXENV=isort
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster
    - env: TOXENV=py37-djangomaster

install:
  - pip install tox
script:
  - tox
